### ISSUE TITLE
Problem requesting permission: Bluetooth Connect

### ISSUE THREAD

**Issue by tyrosinase** [danielgjackson/speaker#2]
Ooh, this seems like a nifty thing for a couple of my audio devices (one of which has the delayed wake-up issue, the other of which needs paired from scratch every time it powers on AND likes to power itself off after being paused for a minute or so). But I get this error when I hit the gear icon, on a Nokia 6.1 (2018) running Android 10.

**Comment by danielgjackson** [comment]
Sorry to hear this. There were some recent changes for newer Android versions, and I may have messed something up!

~~Do you know what the error says exactly?~~

Edit: oh, it's the issue title! 🙂

If you tap and hold the launcher icon, then go to the app information (possibly an ⓘ icon) then *Permissions* and allow the Bluetooth permission manually -- does this work around the issue?

**Comment by tyrosinase** [comment]
Oh, I should have mentioned that: it's not requesting any permissions (so it's grayed out and I can't even allow it manually).

**Comment by LawsonJohnson** [comment]
I'm having the same issue as well, I'm on Android 11. I also tried to go manually allow the permission, but the app has not requested any.

**Comment by danielgjackson** [comment]
Ok, I think this is fixed in the [latest release 1.5](https://github.com/danielgjackson/speaker/releases) -- please try that APK directly if possible.  (Otherwise, I believe F-Droid should eventually auto-update off the repo tag.)

**Comment by danielgjackson** [comment]
F-Droid has now updated the build there too (to v1.5):

* [F-Droid - Speaker](https://f-droid.org/packages/dev.danjackson.speaker/)

...please let me know if that version (or this repo's release APKs) fix the issue for you.

**Comment by tyrosinase** [comment]
That seems to do it, thanks!

**Comment by danielgjackson** [comment]
Great! Thanks for getting back to me, and I'm glad it's working now.

@LawsonJohnson let me know if the new version is not working for you, and I'll reopen the issue.
