### ISSUE TITLE
App blocked by play protect

### ISSUE THREAD

**Issue by an1ndra** [danielgjackson/speaker#3]
![Screenshot_20220602-205435_Google_Play_Store.png](https://user-images.githubusercontent.com/36324543/171664822-ec6a1da4-652a-4dc6-9891-9a9b338f46d8.png)

**Comment by danielgjackson** [comment]
Hi, please could you say whether you downloaded the app via:

1. Google Play
2. F-Droid
3. Directly installing an APK from this project's GitHub Releases (if so, which version)

Also, if it's possible that you already had a previous version of the same app installed?  (And, if so, if removing it first makes any difference).

Thanks in advance.

**Comment by an1ndra** [comment]
F-Droid
I didn't have previous version.  I was trying to install it for the first time.

**Comment by danielgjackson** [comment]
Ok, well it looks like Play Protect just doesn't know whether to trust the APK the F-Droid installs.  That APK should be build from the source in this repository and, I believe, signed by F-Droid.  I'm not sure I can do anything to fix this.

To install the app, you have a few options:

* Press *Install Anyway* if you trust your installation of F-Droid, this repository's source code, and their build process.

* You can download and install an APK release directly from [this repository's releases](https://github.com/danielgjackson/speaker/releases).

* If you have *Google Play Services*, you can install the [version on the Play Store](https://play.google.com/store/apps/details?id=dev.danjackson.speaker)

Let me know if things don't work out, and I'll re-open the issue.
